### PR TITLE
chore: Updated lodash version

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
Updated lodash version to address security vulnerabilities.

Addresses #153 (unless you'd rather switch to using a caret)

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
As mentioned in previous PRs, the Travis build is failing since they don't allow secure environment variables from forks.  I've typically handled this in my OSS project by wrapping https://github.com/mattallty/Caporal.js/blob/master/.travis.yml#L14 in an if.  Something like...

```
- if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage; fi
```

**Comment by Blackbaud-BobbyEarl** [comment]
Anything else I could do to help move this along @mattallty?  Thanks!

**Comment by mjpitz** [comment]
@mattallty : I have a few projects that are complaining about this vulnerability. Do we have an ETA on when to expect a new version?

**Comment by markmarkyesyes** [comment]
@mattallty My company is also waiting for this PR to clear up our security scans. Is there anything we can do to help?

**Comment by mattallty** [comment]
Thank you @Blackbaud-BobbyEarl for the PR, and all for your patience. Will switch on using caret in the future but for now it will do the job!

**Pull request merged**
