### PR TITLE
Promise based validation of arguments and options

### LINKED ISSUE #137: Support promise based validation
Like with the completion feature, it would be nice to support promise based validation of arguments/options.

### Example usage

***Update 5/1/19*** Usage now matches up with how the function validator is supposed to work, had misunderstood this.
``` typescript
function fetchAllNames(): Promise<string[]> {
  ...
}

command('commandname')
  .argument(
    '<name>', 
    'name from a dynamic list of possible names', 
    arg => fetchAllNames().then(names => {
      if (names.includes(arg)) {
        return arg;
      }
      throw new Error(`Valid names are [${names.join(', ')]`);
    })
  )
```

### PR DESCRIPTION
**Pull request by gcox**
Resolves #137 

Adding support for returning a promise from function based argument and option validators

- [x] Argument support
- [x] Option support (WIP)

I chose to continue to allow `validator.validate(?)` to be able to return non-promise results to reduce the external impact, both in the tests and actual usage, of this change. Doing so makes the internals a bit more complex since we have to check whether the result of several calls are promises or not, then take appropriate action. I'm not sure if going the other route, converting `validator.validate(?)` to always return a promise, would have been a breaking change for users but it would have certainly required modifying many of the existing tests.

### CODE REVIEW

**Comment by gcox** [comment]
@mattallty Thanks for checking it out quickly! The changes have been made and failing tests fixed.

**Comment by gcox** [comment]
Also, do you want the commit comments rewritten? Wasn't sure what prefix to use, and now there's a mix of them ('feat(arguments)', 'feat(options)', 'feat(promise-validation)'). Seems like it should probably just be 'feat(promise-validation)'.

**Comment by mattallty** [comment]
`feat(validator): Promise based validation of arguments and options` should be good, thanks !

**Comment by mattallty** [comment]
One more thing: I see 2 "Unhandled rejection" (promise related) in the test logs, doesn't seem good even if test are passing, as in future versions of node.js, unhandled rejections will cause node.js process to exit.

https://travis-ci.org/mattallty/Caporal.js/jobs/527350998#L1554

**Pull request merged**
