### PR TITLE
feat: Implicit boolean option

### LINKED ISSUE #107: Option with no value?
Is it possible to use this to create an option which does not take a value?  For instance, I'd like to add a flag like `--do-stuff` which will be treated as a boolean value when it exists in the arguments for the program.  Here's an example of how I'd use it:

```javascript
program
  .command('myapp')
    .option('--do-stuff')
    .action(({}, { doStuff }, logger) => {
      if(doStuff) {
        logger.info('do stuff');
      } else {
        logger.info('stay put');
      }
    });
```

Then interacting with that flag from the command line would look like this:
```
$ myapp --do-stuff
do stuff
$ myapp
stay put
```

Is this supported already and I am missing something?  Thanks a bunch!

### PR DESCRIPTION
**Pull request by masnagam**
A option which doesn't take a value is called as an implicit boolean
option.

A typical implicit boolean option is defined like below:

```
program
  .command('command', 'Command')
  .option('-f, --flag', 'Flag')
  ...
```

The default value of any implicit boolean option is always `true` even
though a value other than `false` is explicitly specified as its
default value.

There is no meaning to specify arguments other than `synopsis` and
`description`.  Because:

* `validator`: The option has no value to be validate
* `defaultValue`: The default value is always `false`
* `required`: Setting it `true` always makes the option value `true`

This patch together with mattallty/micromist#2 can fix #107.

### CODE REVIEW

**Comment by masnagam** [comment]
Please update package.json and package-lock.json after mattallty/micromist#2 has been merged

**Comment by masnagam** [comment]
No, I have had no feedback.

**Comment by yowainwright** [comment]
@masnagam thanks for your efforts.

**Comment by mattallty** [comment]
Hi @masnagam, thank you very much for this PR !

Could you please:
- update micromist to 1.1.0 (juste released it a few days ago)
- also seems like tests are not run anymore using `npm run test`, like the file issue-107-implicit-boolean-option.js you added had overwritten all other tests :-/ (if your run `npm test` on master, all is fine)

**Comment by mattallty** [comment]
Forgot my last comment, done it :)

**Comment by mattallty** [comment]
@masnagam One test does not pass, see: https://travis-ci.org/mattallty/Caporal.js/jobs/440829899#L2575

**Comment by masnagam** [comment]
@mattallty I've fixed the test failures

**Comment by mattallty** [comment]
Merged, thanks a lot @masnagam for this ! 👍

**Pull request merged**
