### PR TITLE
ci: add docs folders to npmignore

### PR DESCRIPTION
**Pull request by vlaraort**
Fixes https://github.com/mattallty/Caporal.js/issues/113
As looks that is not really solved.

It also solves this retireJS errors:
https://github.com/twbs/bootstrap/issues/28236
https://github.com/twbs/bootstrap/issues/20184
https://github.com/jquery/jquery/issues/2432

### CODE REVIEW

**Comment by vlaraort** [comment]
Looks like travis have some kind of outddated token :(

**Comment by pepocivs** [comment]
Yes, please apply this changes!

**Comment by digodiego8** [comment]
Please, this change will be great!

**Comment by EduRomoGO** [comment]
That would help a lot.

**Pull request merged**
